 const products = [
            { id: 'lp8', name: 'Dell Latitude 5440', price: '890$', img: 'images/product/laptop8.png' },
            { id: 'lp2', name: 'Lenovo Yoga 7i Gen 8', price: '1,150$', img: 'images/product/laptop2.png' },
            { id: 'lp3', name: 'Lenovo Swift X 14', price: '950$', img: 'images/product/laptop3.png' },
            { id: 'lp4', name: 'HP Pavilion Gaming 15', price: '1,080$', img: 'images/product/laptop4.png' },
            { id: 'lp5', name: 'ASUS VivoBook S 15', price: '780$', img: 'images/product/laptop5.png' },
            { id: 'lp6', name: 'Dell G15 5530 Gaming', price: '1,250$', img: 'images/product/laptop6.png' },
            { id: 'lp7', name: 'MSI Katana 15 B13V', price: '1,450$', img: 'images/product/laptop7.png' },
            { id: 'lp8', name: 'Dell Latitude 5440', price: '890$', img: 'images/product/laptop8.png' },
            { id: 'lp9', name: 'Dell Inspiron 16 7630', price: '920$', img: 'images/product/laptop9.png' },
            { id: 'lp10', name: 'Samsung Galaxy Book3 Pro', price: '1,350$', img: 'images/product/laptop10.png' },
            { id: 'lp11', name: 'ASUS ROG Zephyrus G14', price: '1,650$', img: 'images/product/laptop11.png' },
            { id: 'lp4', name: 'HP Pavilion Gaming 15', price: '1,080$', img: 'images/product/laptop4.png' },
            { id: 'lp13', name: 'HP Victus 16 Gaming', price: '1,020$', img: 'images/product/laptop13.png' },
            { id: 'lp14', name: 'Razer Blade 14', price: '2,399$', img: 'images/product/laptop14.png' },
            { id: 'lp15', name: 'Microsoft Surface Laptop 5', price: '1,100$', img: 'images/product/laptop15.png' },
            { id: 'lp16', name: 'Gigabyte G5 Gaming', price: '990$', img: 'images/product/laptop16.png' },
            { id: 'lp17', name: 'MacBook Air M2 Chip', price: '1,099$', img: 'images/product/laptop17.png' },
            { id: 'lp18', name: 'MacBook Pro M3 Max', price: '3,199$', img: 'images/product/laptop18.png' },
            { id: 'lp19', name: 'Alienware m16 R2', price: '1,850$', img: 'images/product/laptop19.png' },
            { id: 'lp20', name: 'Lenovo Legion Slim 5', price: '1,290$', img: 'images/product/laptop20.png' },
            { id: 'lp8', name: 'Dell Latitude 5440', price: '890$', img: 'images/product/laptop8.png' },
            { id: 'lp2', name: 'Lenovo Yoga 7i Gen 8', price: '1,150$', img: 'images/product/laptop2.png' },
            { id: 'lp3', name: 'Lenovo Swift X 14', price: '950$', img: 'images/product/laptop3.png' },
            { id: 'lp4', name: 'HP Pavilion Gaming 15', price: '1,080$', img: 'images/product/laptop4.png' },
            { id: 'lp5', name: 'ASUS VivoBook S 15', price: '780$', img: 'images/product/laptop5.png' },
            { id: 'lp6', name: 'Dell G15 5530 Gaming', price: '1,250$', img: 'images/product/laptop6.png' },
            { id: 'lp7', name: 'MSI Katana 15 B13V', price: '1,450$', img: 'images/product/laptop7.png' },
            { id: 'lp8', name: 'Dell Latitude 5440', price: '890$', img: 'images/product/laptop8.png' },


            // --- Phones (၁၆ လုံး အပြည့်အစုံ) ---
            { id: 'ph1', name: 'iPhone 15 Pro Max', price: '1,350$', category: 'phone', img: 'images/product/phone1.png' },
            { id: 'ph2', name: 'Samsung Galaxy S24 Ultra', price: '1,200$', category: 'phone', img: 'images/product/phone2.png' },
            { id: 'ph3', name: 'Google Pixel 8 Pro', price: '950$', category: 'phone', img: 'images/product/phone3.png' },
            { id: 'ph4', name: 'Xiaomi 14 Ultra', price: '1,100$', category: 'phone', img: 'images/product/phone4.png' },
            { id: 'ph5', name: 'OnePlus 12', price: '850$', category: 'phone', img: 'images/product/phone5.png' },
            { id: 'ph6', name: 'Vivo X100 Pro', price: '900$', category: 'phone', img: 'images/product/phone6.png' },
            { id: 'ph7', name: 'Oppo Find X7 Ultra', price: '1,050$', category: 'phone', img: 'images/product/phone7.png' },
            { id: 'ph8', name: 'Nothing Phone (2)', price: '650$', category: 'phone', img: 'images/product/phone8.png' },
            { id: 'ph9', name: 'iPhone 15 Plus', price: '999$', category: 'phone', img: 'images/product/phone9.png' },
            { id: 'ph10', name: 'Samsung Galaxy Z Fold 5', price: '1,799$', category: 'phone', img: 'images/product/phone10.png' },
            { id: 'ph11', name: 'Redmi Note 13 Pro+', price: '450$', category: 'phone', img: 'images/product/phone11.png' },
            { id: 'ph12', name: 'Realme GT 5', price: '550$', category: 'phone', img: 'images/product/phone12.png' },
            { id: 'ph13', name: 'Asus ROG Phone 8', price: '1,099$', category: 'phone', img: 'images/product/phone13.png' },
            { id: 'ph14', name: 'Sony Xperia 1 V', price: '1,199$', category: 'phone', img: 'images/product/phone14.png' },
            { id: 'ph15', name: 'Huawei P60 Pro', price: '899$', category: 'phone', img: 'images/product/phone15.png' },
            { id: 'ph16', name: 'Motorola Edge 40', price: '499$', category: 'phone', img: 'images/product/phone16.png' }
        ];
